# Pandas

## Pandas is an important library used in python , which can perform tasks like acessing and manipulation of structured data

In [1]:
import pandas as pd

# Read CSV as a DataFrame- which is the representation of data in a tabular form

In [2]:
df=pd.read_csv("services.csv")

In [3]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [4]:
#Check the type of df

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
#see all the columns in df
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [7]:
type(df.columns)

pandas.core.indexes.base.Index

In [8]:
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [9]:
type(list(df.columns))

list

In [10]:
# Check the Data Types of columns

In [11]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [12]:
# Access a particular colums in df
df["fees"]

0     $2.50 suggested donation for lunch for age 60 ...
1     None. Donations requested of clients who can a...
2                                                 None.
3     Vary according to income ($5-$90). Cash, check...
4         $60 application fee. Cash or checks accepted.
5     $55 per year membership dues. Classes have fee...
6     $85 per day. Vary according to income for thos...
7     Suggested donation of $4.25 per meal for senio...
8                                                 None.
9                                                 None.
10                                                None.
11                                                None.
12                                                None.
13                                                None.
14                                                None.
15    None for emergency services. Vary for after sc...
16                                                None.
17                                                None.
18                                                None.
19                                                  NaN
20                                                  NaN
21    None, except for permits and photocopying. Cas...
22    None, except for permits and photocopying. Cas...
Name: fees, dtype: object

In [13]:
type(df["fees"])

pandas.core.series.Series

In [14]:
df[["fees"]]

                                                 fees
0   $2.50 suggested donation for lunch for age 60 ...
1   None. Donations requested of clients who can a...
2                                               None.
3   Vary according to income ($5-$90). Cash, check...
4       $60 application fee. Cash or checks accepted.
5   $55 per year membership dues. Classes have fee...
6   $85 per day. Vary according to income for thos...
7   Suggested donation of $4.25 per meal for senio...
8                                               None.
9                                               None.
10                                              None.
11                                              None.
12                                              None.
13                                              None.
14                                              None.
15  None for emergency services. Vary for after sc...
16                                              None.
17                                              None.
18                                              None.
19                                                NaN
20                                                NaN
21  None, except for permits and photocopying. Cas...
22  None, except for permits and photocopying. Cas...

In [15]:
type(df[["fees"]])

pandas.core.frame.DataFrame

In [16]:
#Access more than 1 column at a time

In [17]:
df["name","fees"]

KeyError: ('name', 'fees')

In [18]:
# we have to use double brackets to view multi columns [[ ]]
df[["name","fees"]]

,name,fees
0,Fair Oaks Adult Activity Center,$2.50 suggested donation for lunch for age 60 ...
1,Second Career Employment Program,None. Donations requested of clients who can a...
2,Senior Peer Counseling,None.
3,Family Visitation Center,"Vary according to income ($5-$90). Cash, check..."
4,Economic Self-Sufficiency Program,$60 application fee. Cash or checks accepted.
5,Little House Recreational Activities,$55 per year membership dues. Classes have fee...
6,Rosener House Adult Day Services,$85 per day. Vary according to income for thos...
7,Meals on Wheels - South County,Suggested donation of $4.25 per meal for senio...
8,Fair Oaks Branch,None.
9,Main Library,None.
10,Schaberg Branch,None.
11,Project Read,None.
12,Redwood Shores Branch,None.
13,Redwood City Corps,None.
14,Adult Rehabilitation Center,None.
15,Sunnyvale Corps,None for emergency services. Vary for after sc...
16,South San Francisco Citadel Corps,None.
17,Project Smile,None.
18,San Mateo Free Medical Clinic,None.
19,Service with blank fields,NaN
20,Service for Admin Test Location,NaN
21,Passport Photos,"None, except for permits and photocopying. Cas..."
22,Example Service Name,"None, except for permits and photocopying. Cas..."

In [19]:
type(df[["name","fees"]])

pandas.core.frame.DataFrame

# Now read data from a table which is available in external website

In [20]:
!pip install lxml

Requirement already satisfied: lxml in /opt/conda/lib/python3.10/site-packages (4.9.2)

In [22]:
import lxml
urld=pd.read_html("http://www.howstat.com/cricket/Statistics/Batting/BattingMostHundredsVsOneCountry.asp")

In [31]:
urld

[    0                                                  1
 0 NaN  Test Cricket - Batting Records and Statistics ...,
                                                    0
 0  Test Cricket - Batting Records and Statistics ...,
                                                    0   1
 0  Players Scoring Most 100s against One Country ... NaN,
       0                    1             2             3    4     5   6   \
 0    NaN               Player       Country        Versus  Mat  Inns  NO
 1    1.0          D G Bradman     Australia       England   37    63   7
 2    2.0         S M Gavaskar         India   West Indies   27    48   6
 3    3.0            J B Hobbs       England     Australia   41    71   4
 4    4.0        S R Tendulkar         India     Australia   39    74   8
 5    5.0         S P D Smith*     Australia       England   32    56   5
 6    6.0       K C Sangakkara     Sri Lanka      Pakistan   23    45   6
 7    7.0            S R Waugh     Australia       England   46    73  18
 8    8.0         G S A Sobers   West Indies       England   36    61   8
 9    9.0       R B Richardson   West Indies     Australia   29    48   4
 10  10.0        S R Tendulkar         India     Sri Lanka   25    36   3
 11  11.0             B C Lara   West Indies     Australia   30    56   2
 12  12.0            D I Gower       England     Australia   42    77   4
 13  13.0          W R Hammond       England     Australia   33    58   3
 14  14.0         G S Chappell     Australia       England   35    65   8
 15  15.0            J E Root*       England         India   25    45   5
 16  16.0         S P D Smith*     Australia         India   16    32   5
 17  17.0          Younis Khan      Pakistan     Sri Lanka   29    48   4
 18  18.0  D P M D Jayawardene     Sri Lanka       England   23    41   3
 19  19.0          R T Ponting     Australia       England   35    58   2
 20  20.0          R T Ponting     Australia         India   29    51   4
 21  21.0          R T Ponting     Australia  South Africa   26    48   3
 22  22.0           J H Kallis  South Africa   West Indies   24    43  11
 23  23.0           J H Kallis  South Africa       England   31    51   3
 24  24.0         P A de Silva     Sri Lanka      Pakistan   21    38   3
 25  25.0           A R Border     Australia       England   47    82  19
 26  26.0           R N Harvey     Australia  South Africa   14    23   3
 27  27.0          G A Headley   West Indies       England   16    29   3
 28  28.0         S M Gavaskar         India     Australia   20    31   1
 29  29.0           A R Morris     Australia       England   24    43   2
 30  30.0          H Sutcliffe       England     Australia   27    46   5
 31  31.0       I V A Richards   West Indies       England   36    50   4
 32  32.0       I V A Richards   West Indies         India   28    41   3
 33  33.0         G S A Sobers   West Indies         India   18    30   7

       7     8     9    10  11     12
 0   Runs    HS  100s  50s  0s    Avg
 1   5028   334    19   12   6  89.79
 2   2749  236*    13    7   5  65.45
 3   3636   187    12   15   3  54.27
 4   3630  241*    11   16   4  55.00
 5   3044   239    11   11   2  59.69
 6   2911   230    10   12   2  74.64
 7   3200  177*    10   14   6  58.18
 8   3214   226    10   13   6  60.64
 9   2175   182     9    7   3  49.43
 10  1995   203     9    6   0  60.45
 11  2815   277     9   11   5  52.13
 12  3269   215     9   12   3  44.78
 13  2852   251     9    7   2  51.85
 14  2619   144     9   12   4  45.95
 15  2526   218     9   10   1  63.15
 16  1813   192     8    5   2  67.15
 17  2286   313     8    6   3  51.95
 18  2212  213*     8   10   2  58.21
 19  2476   196     8    9   2  44.21
 20  2555   257     8   12   4  54.36
 21  2132  143*     8   11   6  47.38
 22  2356   177     8   12   3  73.63
 23  2141  182*     8    8   4  44.60
 24  1475   168     8    1   3  42.14
 25  3548  200*     8   21   3  56.32
 26  1625   205     8    5   0  81.25
 27  1852  270*     8    5   1  71.23
 28  1550   172     8    4   2  51.67
 29  2080   206     8    8   3  50.73
 30  2741   194     8   16   1  66.85
 31  2869   291     8   15   2  62.37
 32  1927  192*     8    7   1  50.71
 33  1920   198     8    7   2  83.48  ,
                                      0
 0  Batting Records and Statistics Menu]

In [32]:
type(urld)

list

In [33]:
len(urld)

5

In [30]:
urld[3]

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,Player,Country,Versus,Mat,Inns,NO,Runs,HS,100s,50s,0s,Avg
1,1.0,D G Bradman,Australia,England,37,63,7,5028,334,19,12,6,89.79
2,2.0,S M Gavaskar,India,West Indies,27,48,6,2749,236*,13,7,5,65.45
3,3.0,J B Hobbs,England,Australia,41,71,4,3636,187,12,15,3,54.27
4,4.0,S R Tendulkar,India,Australia,39,74,8,3630,241*,11,16,4,55.00
5,5.0,S P D Smith*,Australia,England,32,56,5,3044,239,11,11,2,59.69
6,6.0,K C Sangakkara,Sri Lanka,Pakistan,23,45,6,2911,230,10,12,2,74.64
7,7.0,S R Waugh,Australia,England,46,73,18,3200,177*,10,14,6,58.18
8,8.0,G S A Sobers,West Indies,England,36,61,8,3214,226,10,13,6,60.64
9,9.0,R B Richardson,West Indies,Australia,29,48,4,2175,182,9,7,3,49.43
10,10.0,S R Tendulkar,India,Sri Lanka,25,36,3,1995,203,9,6,0,60.45
11,11.0,B C Lara,West Indies,Australia,30,56,2,2815,277,9,11,5,52.13
12,12.0,D I Gower,England,Australia,42,77,4,3269,215,9,12,3,44.78
13,13.0,W R Hammond,England,Australia,33,58,3,2852,251,9,7,2,51.85
14,14.0,G S Chappell,Australia,England,35,65,8,2619,144,9,12,4,45.95
15,15.0,J E Root*,England,India,25,45,5,2526,218,9,10,1,63.15
16,16.0,S P D Smith*,Australia,India,16,32,5,1813,192,8,5,2,67.15
17,17.0,Younis Khan,Pakistan,Sri Lanka,29,48,4,2286,313,8,6,3,51.95
18,18.0,D P M D Jayawardene,Sri Lanka,England,23,41,3,2212,213*,8,10,2,58.21
19,19.0,R T Ponting,Australia,England,35,58,2,2476,196,8,9,2,44.21
20,20.0,R T Ponting,Australia,India,29,51,4,2555,257,8,12,4,54.36
21,21.0,R T Ponting,Australia,South Africa,26,48,3,2132,143*,8,11,6,47.38
22,22.0,J H Kallis,South Africa,West Indies,24,43,11,2356,177,8,12,3,73.63
23,23.0,J H Kallis,South Africa,England,31,51,3,2141,182*,8,8,4,44.60
24,24.0,P A de Silva,Sri Lanka,Pakistan,21,38,3,1475,168,8,1,3,42.14
25,25.0,A R Border,Australia,England,47,82,19,3548,200*,8,21,3,56.32
26,26.0,R N Harvey,Australia,South Africa,14,23,3,1625,205,8,5,0,81.25
27,27.0,G A Headley,West Indies,England,16,29,3,1852,270*,8,5,1,71.23
28,28.0,S M Gavaskar,India,Australia,20,31,1,1550,172,8,4,2,51.67
29,29.0,A R Morris,Australia,England,24,43,2,2080,206,8,8,3,50.73
30,30.0,H Sutcliffe,England,Australia,27,46,5,2741,194,8,16,1,66.85
31,31.0,I V A Richards,West Indies,England,36,50,4,2869,291,8,15,2,62.37
32,32.0,I V A Richards,West Indies,India,28,41,3,1927,192*,8,7,1,50.71
33,33.0,G S A Sobers,West Indies,India,18,30,7,1920,198,8,7,2,83.48

# Now let's save the above data to a csv file

In [34]:
urld[3].to_csv("crick.csv",header=Fa)